# Generated by Django 5.2 on 2025-04-28 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.PositiveSmallIntegerField()),
                ('humidity', models.PositiveSmallIntegerField()),
                ('light', models.PositiveSmallIntegerField()),
                ('soil_moisture', models.PositiveSmallIntegerField()),
                ('pump_power', models.BooleanField()),
                ('reservoir_level', models.PositiveSmallIntegerField()),
                ('errors', models.CharField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Warning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to='plantmonitor.measurement')),
            ],
        ),
    ]
