# Generated by Django 5.2 on 2025-05-01 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantmonitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThresholdPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moisture_threshold', models.IntegerField(default=350)),
                ('reservoir_threshold', models.IntegerField(default=8)),
            ],
        ),
    ]
